const blessed = require('neo-blessed');
const config = require('../config');
const I = config.ICONS;

function createHelpOverlay(screen) {
  const box = blessed.box({
    parent: screen,
    top: 1,
    left: 'center',
    width: 82,
    height: '100%-2',
    hidden: true,
    tags: true,
    border: { type: 'line' },
    style: {
      border: { fg: 'cyan' },
      bg: 'black',
    },
    label: ` ${I.skill} CC-Monitor Help  {gray-fg}[↑↓ scroll]{/gray-fg} `,
    scrollable: true,
    alwaysScroll: true,
    scrollbar: {
      ch: '█',
      style: { bg: 'cyan' },
      track: { bg: 'black' },
    },
    mouse: true,
    keys: false,
    vi: false,
  });

  const S = '{gray-fg}' + '─'.repeat(76) + '{/gray-fg}';

  const content = [
    '',
    '  {bold}{cyan-fg}██  CC-Monitor{/cyan-fg}{/bold}  {gray-fg}Claude Code Session Monitor{/gray-fg}',
    '',
    '  Claude Code 세션을 실시간 모니터링하는 TUI 대시보드.',
    '  세션이 실행 중이면 자동 감지되어 2초 주기로 갱신됩니다.',
    '  모든 파일은 read-only로만 읽습니다 — Claude Code 데이터를 수정하지 않습니다.',
    '',
    '',
    S,
    `  {bold}{yellow-fg}☰  빠른 시작{/yellow-fg}{/bold}`,
    S,
    '',
    '  1. Claude Code 세션을 어딘가에서 실행 상태로 둔다',
    '  2. 이 모니터 실행 → 자동 감지 (활성 세션이 여러 개면 상단 ↑↓로 전환)',
    '  3. 탭 `1`로 한눈에 상태 보기 → `2` Flow로 이벤트 흐름 → `5` Tree로 에이전트 계층',
    '  4. 문제 의심되면 Subagents 패널의 진단 라인이나 Tree 탭 Details 확인',
    '',
    '',
    S,
    `  {bold}{yellow-fg}☰  공통 키보드{/yellow-fg}{/bold}`,
    S,
    '',
    '  {bold}탭 전환{/bold}',
    '    {bold}{cyan-fg}1{/cyan-fg}{/bold} Overview   {bold}{cyan-fg}2{/cyan-fg}{/bold} Flow   {bold}{cyan-fg}3{/cyan-fg}{/bold} Config   {bold}{cyan-fg}4{/cyan-fg}{/bold} Metrics   {bold}{cyan-fg}5{/cyan-fg}{/bold} Tree   {bold}{cyan-fg}6{/cyan-fg}{/bold} Teams',
    '',
    '  {bold}공통 키{/bold}',
    '    {bold}{cyan-fg}?{/cyan-fg}{/bold}          도움말 열기/닫기',
    '    {bold}{cyan-fg}n{/cyan-fg}{/bold}          현재 세션에 이름 붙이기 (여러 세션 구분용)',
    '    {bold}{cyan-fg}r{/cyan-fg}{/bold}          새로고침 (캐시 초기화 후 재읽기)',
    '    {bold}{cyan-fg}q{/cyan-fg}{/bold} / {bold}{cyan-fg}ESC{/cyan-fg}{/bold}    종료',
    '',
    '  {bold}탭 의존 키{/bold}  {gray-fg}— 같은 키가 탭마다 다르게 동작{/gray-fg}',
    '    {bold}{cyan-fg}↑↓{/cyan-fg}{/bold}   Tab 1: 세션 전환 (다중 세션 시)',
    '           Tab 2/3/4: 해당 패널 1줄 스크롤 (정밀)',
    '           Tab 5: 노드 선택 커서 이동',
    '           Tab 6: Gantt 패널 스크롤',
    '           Help: 도움말 1줄 스크롤',
    '    {bold}{cyan-fg}h f m s u{/cyan-fg}{/bold}  Tab 2 이벤트 필터 토글 (Hook/Rule/Memory/Skill/User)',
    '    {bold}{cyan-fg}a{/cyan-fg}{/bold}         Tab 5 완료 에이전트 표시 토글 (recent ↔ all)',
    '    {bold}{cyan-fg}[{/cyan-fg}{/bold} {bold}{cyan-fg}]{/cyan-fg}{/bold}     Tab 5/6 세션 전환 (↑↓가 다른 용도라 별도 키)',
    '',
    '  {bold}스크롤 보조 키{/bold}  {gray-fg}(스크롤되는 모든 탭 + 도움말){/gray-fg}',
    '    {bold}{cyan-fg}PgUp{/cyan-fg}{/bold} / {bold}{cyan-fg}PgDn{/cyan-fg}{/bold}   페이지 단위 점프',
    '    {bold}{cyan-fg}Home{/cyan-fg}{/bold} / {bold}{cyan-fg}End{/cyan-fg}{/bold}    맨 위 / 맨 아래로 이동',
    '',
    '',
    S,
    `  {bold}{yellow-fg}${I.session}  Tab 1 — Overview{/yellow-fg}{/bold}`,
    S,
    '',
    '  한 화면에 세션 전체 상태를 밀도 있게 표시.',
    '',
    `  {bold}{cyan-fg}${I.session} Header{/cyan-fg}{/bold}`,
    '  세션 ID, 모델, 경과/유휴 시간, 메시지 수, 토큰 누적.',
    '',
    '  {bold}Context 프로그레스 바{/bold} — 컨텍스트 윈도우 사용률',
    '    {green-fg}███{/green-fg} <80%   정상',
    '    {yellow-fg}███{/yellow-fg} 80~89% 주의 {gray-fg}— compaction 임박{/gray-fg}',
    '    {red-fg}███{/red-fg} 90%+   위험 {gray-fg}— 곧 compaction 발생{/gray-fg}',
    '',
    `  {bold}{cyan-fg}${I.tool} Tools & Files{/cyan-fg}{/bold}`,
    '  도구별 호출 횟수 + 파일 활동 막대그래프 {gray-fg}(Read/Write/Search){/gray-fg}',
    '  진행바는 터미널 너비에 반응형으로 자동 조정.',
    '',
    `  {bold}{cyan-fg}${I.agent} Subagents{/cyan-fg}{/bold}  {gray-fg}— 에이전트 수에 따라 패널 높이 자동 조절{/gray-fg}`,
    '',
    '  {bold}에이전트 유형{/bold} {gray-fg}(Agent 도구의 subagent_type){/gray-fg}:',
    '    {bold}general-purpose{/bold}  범용 (코드 탐색, 멀티스텝 작업)',
    '    {bold}Explore{/bold}          코드베이스 탐색 특화 (빠른 검색)',
    '    {bold}Plan{/bold}             구현 계획 설계',
    '    {bold}code-reviewer{/bold}    코드 리뷰',
    '    {bold}code-simplifier{/bold}  코드 정리/리팩토링',
    '    {bold}feature-dev:*{/bold}    기능 개발 세부 역할 (code-explorer, code-architect 등)',
    '',
    '  {bold}한 줄 읽기{/bold}:',
    '    {green-fg}●{/green-fg} {bold}general-purpose{/bold}  {magenta-fg}opus{/magenta-fg}  {cyan-fg}  5m 3s{/cyan-fg}  {gray-fg}1.8M/7.0K  Read:17 Bash:14{/gray-fg}',
    '    │        │                │     │         │            │',
    '    상태     유형             모델  경과시간  토큰In/Out   도구 Top3',
    '',
    '  {bold}상태 아이콘{/bold}:',
    '    {green-fg}●{/green-fg} 실행 중      {gray-fg}✓{/gray-fg} 완료',
    '',
    '  {bold}병목 경고{/bold} {gray-fg}(에이전트 라인 뒤에 표시){/gray-fg}:',
    `    {red-fg}${I.warn} slow(5m){/red-fg}       5분 이상 실행 중 — stuck 가능성`,
    `    {yellow-fg}${I.warn} search-heavy{/yellow-fg}   도구의 70%+가 검색(Read/Grep/Glob)`,
    `    {yellow-fg}${I.warn} high-tokens{/yellow-fg}    입력 토큰 500K 초과 — 비용 주의`,
    '',
    '  {bold}진단 라인{/bold} {gray-fg}(실행 중 에이전트만 표시){/gray-fg}:',
    `    {red-fg}${I.warn} LOOP  Grep x9{/red-fg}       동일 도구 반복 호출 — 루프 가능성`,
    `    {red-fg}${I.warn} DENY  x2{/red-fg}            권한 거부된 도구 호출`,
    `    {yellow-fg}${I.warn} ERR(3)  msg...{/yellow-fg}   에러 횟수 + 마지막 에러 메시지`,
    `    {gray-fg}${I.read} "파일 구조 탐색 중..."{/gray-fg}  현재 활동 (마지막 텍스트)`,
    '',
    '  {gray-fg}참고: "Exit code", "Cancelled" 같은 일반 프로세스 결과는 필터링됨{/gray-fg}',
    '',
    `  {bold}{cyan-fg}${I.msg} Recent Conversation{/cyan-fg}{/bold}`,
    '  최근 대화 쌍 (User 질문 + AI 응답 요약). 최근 10쌍까지.',
    '',
    `  {bold}{cyan-fg}${I.recap} Recap{/cyan-fg}{/bold}`,
    '  Context compaction 히스토리 및 대화 요약.',
    '  토큰 변화(pre→post), 사용자 메시지 요약, 진행 중 작업을 묶어서 보여줌.',
    '',
    `  {bold}{cyan-fg}${I.cost} Cost{/cyan-fg}{/bold}`,
    '  오늘 총 비용:  {green-fg}$0~19{/green-fg} 정상   {yellow-fg}$20~49{/yellow-fg} 주의   {red-fg}$50+{/red-fg} 높음',
    '  ~/.claude/powerline/usage/today.json 에서 읽어옴.',
    '',
    '',
    S,
    `  {bold}{yellow-fg}${I.tool}  Tab 2 — Flow{/yellow-fg}{/bold}`,
    S,
    '',
    '  세션의 rules, hooks, skills, memory 로드/실행을 시간순으로 추적.',
    '  연속된 PostToolUse hook은 한 줄로 그룹핑됨 (예: "PostToolUse x12 (Read:5 Bash:7)").',
    '',
    '  {bold}아이콘{/bold}:',
    '    {cyan-fg}▶ [USER ]{/cyan-fg}   사용자 메시지',
    '    {green-fg}✓ [HOOK ]{/green-fg}   Hook 성공  {gray-fg}(SessionStart, UserPromptSubmit 등){/gray-fg}',
    '    {gray-fg}✗ [HOOK ]{/gray-fg}   Hook 취소/실패',
    '    {yellow-fg}☰ [RULE ]{/yellow-fg}   Rule 로드  {gray-fg}(.claude/rules/*.md){/gray-fg}',
    '    {magenta-fg}★ [MEM  ]{/magenta-fg}   Memory 로드  {gray-fg}(~/.claude/memory/*.md){/gray-fg}',
    '    {green-fg}✦ [SKILL]{/green-fg}   스킬 호출   {gray-fg}(/brainstorming, /systematic-debugging 등){/gray-fg}',
    '    {cyan-fg}↻ [RECAP]{/cyan-fg}   Context compaction 발생',
    '',
    '  {bold}필터 키{/bold} {gray-fg}(Flow 탭에서만 동작, 토글){/gray-fg}:',
    '    {bold}{cyan-fg}h{/cyan-fg}{/bold} Hook    {bold}{cyan-fg}f{/cyan-fg}{/bold} Rule    {bold}{cyan-fg}m{/cyan-fg}{/bold} Memory    {bold}{cyan-fg}s{/cyan-fg}{/bold} Skill    {bold}{cyan-fg}u{/cyan-fg}{/bold} User',
    '    활성 필터는 하단 상태바에 ● 표시, 비활성은 ○ 표시.',
    '',
    '  {bold}활용{/bold}: "왜 이 스킬이 호출됐지?" → skill 이벤트 앞의 hook/rule 확인',
    '       "훅이 제대로 불렸나?" → h 필터만 켜고 SessionStart/UserPromptSubmit 확인',
    '',
    '',
    S,
    `  {bold}{yellow-fg}${I.session}  Tab 3 — Config{/yellow-fg}{/bold}`,
    S,
    '',
    '  세션과 무관하게 Claude Code 전역 설정을 트리 구조로 표시.',
    '  ~/.claude/ 디렉토리와 프로젝트 .claude/ 의 파일을 실시간으로 읽어 보여줍니다.',
    '',
    '  {bold}표시 항목{/bold}:',
    `    {bold}{cyan-fg}📄 CLAUDE.md{/cyan-fg}{/bold}   project(프로젝트 루트) + user(~/.claude/CLAUDE.md)`,
    `    {bold}{cyan-fg}📏 Rules{/cyan-fg}{/bold}       ~/.claude/rules/*.md 및 프로젝트 .claude/rules/*.md`,
    `    {bold}{cyan-fg}🔗 Hooks{/cyan-fg}{/bold}       settings.json의 hooks 설정 (SessionStart, PostToolUse 등)`,
    `    {bold}{cyan-fg}⚡ Skills{/cyan-fg}{/bold}      ~/.claude/skills/*/skill.md 목록`,
    `    {bold}{cyan-fg}🔌 MCP Servers{/cyan-fg}{/bold} settings.json의 enabledMcpjsonServers 등`,
    `    {bold}{cyan-fg}◈ Plugins{/cyan-fg}{/bold}    settings.json의 enabledPlugins`,
    `    {bold}{cyan-fg}🧠 Memory{/cyan-fg}{/bold}     ~/.claude/memory/*.md 목록`,
    '',
    '  {bold}스크롤{/bold}: ↑↓ 로 긴 트리를 위/아래로 이동',
    '',
    '',
    S,
    `  {bold}{yellow-fg}${I.skill}  Tab 4 — Skill Metrics{/yellow-fg}{/bold}`,
    S,
    '',
    '  스킬별 호출 통계를 테이블로 표시. 어느 스킬을 자주 쓰고 어느 스킬이 사멸했는지 한눈에.',
    '  데이터 소스: ~/.claude/skill-calls.jsonl (PostToolUse hook의 skill-tracker가 기록).',
    '',
    '  {bold}컬럼 설명{/bold}:',
    '    {bold}상태{/bold}       스킬의 사용 빈도 상태 (아래 참조)',
    '    {bold}스킬명{/bold}     스킬 이름',
    '    {bold}마지막 호출{/bold}  최근 호출 시각의 상대 표현 (예: "5분 전", "3일 전")',
    '    {bold}호출{/bold}       누적 호출 횟수',
    '    {bold}manual%{/bold}    직접 호출(명시 호출) 비율 — 나머지는 자동 활성',
    '    {bold}출처{/bold}       custom(사용자) / plugin(플러그인)',
    '',
    '  {bold}상태 분류{/bold}:',
    '    {green-fg}🟢 active{/green-fg}    최근 활발하게 사용 중',
    '    {yellow-fg}🟡 dormant{/yellow-fg}   한동안 호출 없음 — 휴면 상태',
    '    {red-fg}🔴 dead{/red-fg}      매우 오랫동안 호출 없음 — 제거 후보',
    '    {gray-fg}⚫ unused{/gray-fg}    설치 후 한 번도 호출 안 됨',
    '    {cyan-fg}🆕 new{/cyan-fg}       최근 설치/등록된 신규 스킬',
    '',
    '  {bold}경고 마커{/bold}:',
    `    {red-fg}auto only{/red-fg}   manual% = 0% — 자동으로만 불리고 직접 호출 0건.`,
    '                → 사용자가 존재를 모르는 상태일 가능성, 사멸 후보',
    '',
    '  {bold}활용{/bold}: dead 또는 auto only 스킬은 정리 후보로 메모',
    '       active 스킬의 manual%가 낮다 → 자동 활성화가 잘 작동 중',
    '',
    '  {bold}스크롤{/bold}: ↑↓ 로 긴 테이블 이동',
    '',
    '',
    S,
    `  {bold}{yellow-fg}${I.agent}  Tab 5 — Tree{/yellow-fg}{/bold}`,
    S,
    '',
    '  활성 세션의 서브에이전트 계층 구조를 실시간 트리로 표시.',
    '  메인 세션이 Agent 도구로 서브에이전트를 spawn하고, 그 서브에이전트가 또 다른',
    '  서브에이전트를 호출하는 N단계 중첩 관계를 parentToolUseID 링크로 정확히 조립합니다.',
    '',
    '  {bold}레이아웃{/bold}:',
    '    상단 70%: 트리 뷰 (├─ └─ 들여쓰기로 계층 표시)',
    '    하단 30%: Details 패널 — 선택된 노드의 상세 정보',
    '',
    '  {bold}노드 표시 형식{/bold} (2~3줄):',
    '    {green-fg}●{/green-fg} {bold}agentType{/bold}  {yellow-fg}sonnet{/yellow-fg}  ◷ 2m 31s  running',
    '         "description 일부 — Agent 호출 시 전달한 설명"',
    '         🛠 Read:12 Grep:8 Bash:2',
    '',
    '  {bold}상태 아이콘{/bold}:',
    `    {cyan-fg}${I.session}{/cyan-fg} session root (최상위 메인)`,
    `    {green-fg}${I.agent}{/green-fg} running (실행 중)`,
    `    {gray-fg}${I.agentDone}{/gray-fg} done (완료)`,
    `    {blue-fg}${I.recap}{/blue-fg} recent done (5분 이내 완료)`,
    `    {red-fg}${I.warn}{/red-fg} error (diagnostics에 에러 있음)`,
    '',
    '  {bold}표시 모드{/bold} ({bold}{cyan-fg}a{/cyan-fg}{/bold} 로 토글):',
    '    {bold}[recent]{/bold}  실행 중 + 최근 완료(5분 이내)만 표시 {gray-fg}— 기본값{/gray-fg}',
    '    {bold}[all]{/bold}     세션 내 모든 에이전트 표시 (긴 트리)',
    '',
    '  {bold}키보드{/bold}:',
    '    {bold}{cyan-fg}↑↓{/cyan-fg}{/bold}    노드 선택 커서 이동 ({bold}{cyan-fg}▶{/cyan-fg}{/bold} 마커)',
    '    {bold}{cyan-fg}a{/cyan-fg}{/bold}     recent ↔ all 모드 토글',
    '    {bold}{cyan-fg}[{/cyan-fg}{/bold} {bold}{cyan-fg}]{/cyan-fg}{/bold}   세션 전환 (다중 세션 시. ↑↓가 커서용이라 별도 키 사용)',
    '',
    '  {bold}Details 패널에 표시되는 것{/bold}:',
    '    선택된 에이전트의 description, 상태, 시작시간, 소요시간, 모델,',
    '    토큰 In/Out, 도구 사용 Top8, 마지막 활동, 에러/권한거부 진단',
    '',
    '  {bold}활용{/bold}:',
    '    • "이 서브에이전트가 또 누구 불렀지?" → 트리에서 자식 노드 확인',
    '    • "에이전트가 뭐 때문에 에러났지?" → ✗ 노드 선택 → Details에서 에러 메시지',
    '    • "병렬 에이전트들이 잘 돌고 있나?" → recent 모드로 러닝 상태만 관찰',
    '',
    '',
    S,
    `  {bold}{yellow-fg}${I.agent}  Tab 6 — Teams (팀 협업 대시보드){/yellow-fg}{/bold}`,
    S,
    '',
    '  "어떤 에이전트가 언제 일했고 / 누가 누굴 불렀고 / 누가 얼마나 부담을 지고',
    '  있으며 / 지금 병목은 어디인지"를 한 화면에 4개 서브패널로 보여줍니다.',
    '  같은 type의 에이전트는 4개 패널에서 모두 같은 색으로 표시됩니다.',
    '',
    '  {bold}1. ⏱  작업 타임라인 (Agent Gantt){/bold}  {gray-fg}— 상단 40%{/gray-fg}',
    '    각 에이전트를 가로 막대로 배치. 가로축은 전체 시간축 (min→max).',
    '    {green-fg}█{/green-fg} 실행 구간, {gray-fg}░{/gray-fg} 대기 구간. 병렬 실행 여부와',
    '    순차 호출 인과를 눈으로 확인 가능.',
    '',
    '  {bold}2. 🔀  호출 플로우 (Orchestration Flow){/bold}  {gray-fg}— 중단 30%{/gray-fg}',
    '    main이 누구를 호출했고, 그 서브에이전트가 또 누구를 호출했는지',
    '    부모-자식 관계를 ├─▶ 트리 형태로 시작 순서대로 표시.',
    '    각 호출의 description / 경과시간 / running 상태를 함께.',
    '',
    '  {bold}3. 📊  팀 작업량 (Team Load){/bold}  {gray-fg}— 하단 좌측{/gray-fg}',
    '    agentType별 집계 막대: 호출 횟수 · 누적 시간 · 토큰 합계 · 도구 호출.',
    '    어느 역할의 에이전트가 가장 많이 일했는지 한눈에.',
    '',
    '  {bold}4. 🔥  병목 히트맵 (Bottleneck){/bold}  {gray-fg}— 하단 우측{/gray-fg}',
    '    "활성도 = 도구 호출 / 분" 으로 계산. 밀도가 높으면 바쁘게 움직이는',
    '    에이전트, 낮으면 대기·병목 가능성. running 중인데 활성도가 낮으면',
    '    {red-fg}{bold}멈춤?{/bold}{/red-fg} 태그가 붙어 병목 지점을 지목합니다.',
    '',
    '  {bold}키보드{/bold}:',
    '    {bold}{cyan-fg}↑↓{/cyan-fg}{/bold}    Gantt 스크롤 (에이전트 수 많을 때)',
    '    {bold}{cyan-fg}[{/cyan-fg}{/bold} {bold}{cyan-fg}]{/cyan-fg}{/bold}   세션 전환 (다중 세션 시)',
    '',
    '  {bold}활용{/bold}:',
    '    • "왜 이 작업이 오래 걸렸지?" → Gantt에서 겹친 구간 확인 → 병렬/직렬 판단',
    '    • "어느 역할이 과부하인가?" → Load에서 큰 막대 + 실행 중 ● 개수',
    '    • "지금 멈춰있는 에이전트?" → Bottleneck의 멈춤? 태그',
    '',
    '',
    S,
    `  {bold}{yellow-fg}${I.warn}  트러블슈팅{/yellow-fg}{/bold}`,
    S,
    '',
    '  {bold}Context > 80%{/bold}',
    '    compaction 임박. 중요 맥락이 있으면 새 세션 시작 고려.',
    '',
    '  {bold}Subagent에 LOOP 경고{/bold}',
    '    동일 도구를 6회+ 반복 호출 중. 에이전트가 동일 파일/패턴을',
    '    반복 탐색하며 stuck된 상태일 수 있음.',
    '',
    '  {bold}Subagent에 ERR 표시{/bold}',
    '    도구 호출 실패 (파일 없음, 권한 부족 등).',
    '    에이전트가 대안 경로를 찾으면 정상. 계속 누적되면 문제.',
    '',
    '  {bold}Cost 급증{/bold}',
    '    Subagents 패널에서 불필요한 루프/높은 토큰 에이전트 확인.',
    '    Tree 탭에서도 노드별 토큰 In/Out 확인 가능.',
    '',
    '  {bold}Idle이 길면{/bold}',
    '    세션이 멈춘 상태이거나 입력 대기 중.',
    '',
    '  {bold}Tab 4 "skill-calls.jsonl 없음"{/bold}',
    '    PostToolUse 훅(skill-tracker.mjs)이 아직 스킬 호출을 기록하지 않음.',
    '    첫 Skill 호출 후 파일이 생성되면 자동으로 표시됨.',
    '',
    '  {bold}Tab 5에 트리가 비어있음{/bold}',
    '    현재 세션에 Agent 도구로 spawn된 서브에이전트가 아직 없음.',
    '    root(메인)만 표시되며 "Waiting for first tool call..." 힌트가 뜰 수 있음.',
    '',
    '',
    S,
    `  {bold}{yellow-fg}⛁  데이터 소스{/yellow-fg}{/bold}`,
    S,
    '',
    '  cc-monitor는 아래 파일만 {bold}읽기 전용{/bold}으로 참조합니다.',
    '  어떤 파일도 수정하지 않습니다.',
    '',
    '    {gray-fg}~/.claude/projects/{/gray-fg}           JSONL 세션 로그 (메시지, 도구, 토큰)',
    '    {gray-fg}~/.claude/sessions/{/gray-fg}           활성 세션 메타데이터 (PID, cwd, 모델)',
    '    {gray-fg}~/.claude/history.jsonl{/gray-fg}       사용자 입력 및 스킬 호출 히스토리',
    '    {gray-fg}~/.claude/skill-calls.jsonl{/gray-fg}   스킬 호출 로그 (Tab 4 데이터 소스)',
    '    {gray-fg}~/.claude/powerline/usage/today.json{/gray-fg}  오늘 API 비용',
    '    {gray-fg}~/.claude/settings.json{/gray-fg}       훅, 권한, 환경변수',
    '    {gray-fg}~/.claude/CLAUDE.md{/gray-fg}           사용자 레벨 지침',
    '    {gray-fg}<프로젝트>/.claude/rules/{/gray-fg}      프로젝트 규칙',
    '    {gray-fg}<프로젝트>/CLAUDE.md{/gray-fg}           프로젝트 지침',
    '',
    '',
    '  ' + S,
    '  {gray-fg}{center}? 또는 ESC 를 눌러 닫기{/center}{/gray-fg}',
  ];

  box.setContent(content.join('\n'));
  return box;
}

module.exports = { createHelpOverlay };
